# Generated by Django 3.0.3 on 2020-05-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_auto_20200525_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
