# Generated by Django 3.0.3 on 2020-05-26 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0004_auto_20200525_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date',
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
